### PR TITLE
add cargo feature for windows hidpi api

### LINKED ISSUE #36: Troubles on Windows 7
Application asks for "api-ms-win-shcore-scaling-l1-1-1.dll" and can't find required file in system32 folder (because Shcore part of windows 8.1, which used for GetDPIForMonitor in AppCore.dll)

Problem happen due to SetProcessDpiAwareness (PROCESS_PER_MONITOR_DPI_AWARE)

This issue happen in Ruffle emulator, we recently updated tinyfiledialogs-rs up to v3.9.0

### PR DESCRIPTION
**Pull request by macpp**
since usage of `ShellScalingApi.h` seems to absent in upsream liblary, it may make sense to add option to disable it (via `default-features=false`) if it doesn't work for whatever reason

fixes #36

### CODE REVIEW

**Comment by jdm** [comment]
This looks like a reasonable solution!

**Comment by macpp** [comment]
Ok, so now hidpi patch works with `git apply` when applying on top tinyfiledialogs.c from 3d997f5d9bad92fe55ef18caf18e5712282ea717. Somehow patch that is currently on master contais diff of itself, so i removed it to make it work (i suppose that it was here by mistake, but tell me if i'm wrong). Also fixed some whitespaces.

**Comment by macpp** [comment]
@jdm Any chance for merging this?

**Review by jdm — APPROVED** [review]

**Comment by macpp** [comment]
Thanks! Do you think that there will be path release any time soon? (would be much apprieciated!)

**Comment by jdm** [comment]
Done.

**Comment by macpp** [comment]
thank you !

**Pull request merged**
